name: Build and Test

inputs:
  github_token:
    description: The Github token to authenticate gh CLI.
    required: true

runs:
  using: composite
  steps:
    - name: Execute Tests
      shell: bash
      env:
        # The tests make use of Github-specific functionality (e.g. gh).
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        bazelisk test ... --test_output=errors
        bazelisk test ... --test_output=errors --enable_bzlmod

    - name: Execute Integration Tests
      shell: bash
      # Bazel-in-Bazel still has issues with runfiles
      if: runner.os != 'Windows'
      env:
        # The tests make use of Github-specific functionality (e.g. gh).
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        bazelisk test :all_integration_tests --test_output=errors
        bazelisk test :all_integration_tests --test_output=errors --enable_bzlmod
