# https://www.stevenengelhardt.com/2023/02/26/practical-bazel-using-bazels-bash-unittest-framework/

sh_library(
    name = "unittest",
    srcs = [
        "unittest.bash",
        "unittest_utils.sh",
    ],
    visibility = ["//visibility:public"],
)