load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

sh_binary(
    name = "generate_assets_declaration",
    srcs = ["generate_assets_declaration.sh"],
    visibility = ["//visibility:public"],
)
