name: CI

on:
  pull_request:
    branches: [ main ]
  schedule:
    # Every day at 11:03 UTC.
    - cron: '3 11 * * *'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        bazel_version: ['9.x', rolling]
    runs-on: ${{ matrix.os }}
    env:
      USE_BAZEL_VERSION: ${{ matrix.bazel_version }}
    steps:
    - uses: actions/checkout@v2
    - name: Execute Tests
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: env && exit 1
