name: CI for PR Merge

on:
  pull_request:
    branches: [ main ]
  schedule:
    # Every day at 11:03 UTC.
    - cron: '3 11 * * *'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        bazel:
          - { version: '7.x', flags: '' }
          - { version: '7.x', flags: '--enable_bzlmod' }
          - { version: '8.x', flags: '--noenable_bzlmod --enable_workspace' }
          - { version: '8.x', flags: '--enable_bzlmod --noenable_workspace' }
          - { version: '9.x', flags: '' }
          - { version: rolling, flags: '' }
    runs-on: ${{ matrix.os }}
    env:
      USE_BAZEL_VERSION: ${{ matrix.bazel.version }}
    steps:
    - uses: actions/checkout@v2
    - name: Set CC
      if: runner.os == 'Linux'
      run: echo "CC=clang" >> "$GITHUB_ENV"
    - name: Execute Tests
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bazelisk test ... --test_output=errors ${{ matrix.bazel.flags }}
    - name: Execute Integration Tests
      shell: bash
      # Bazel-in-Bazel still has issues with runfiles
      if: runner.os != 'Windows'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bazelisk test :all_integration_tests --test_output=errors ${{ matrix.bazel.flags }}
