name: CI for PR Merge

on:
  pull_request:
    branches: [ main ]
  schedule:
    # Every day at 11:03 UTC.
    - cron: '3 11 * * *'

jobs:
  macos_build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_test
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  ubuntu_build:
    runs-on: ubuntu-20.04
    env:
      CC: clang
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_test
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  windows_build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_test
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
