name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: true
        type: string
      base_branch:
        description: The branch being merged to.
        type: string
        default: main

jobs:
  create_release:
    runs-on: ubuntu-latest
    env:
      CC: clang

    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Generate a token that has permission to create a PR to update the README.md.
      - uses: tibdex/github-app-token@v1
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      # Set up the git user to create a comiit (e.g. set user.name and user.email)
      - uses: cgrindel/gha_configure_git_user@v1

      # Create the release
      - uses: cgrindel/gha_create_release@v1
        with:
          release_tag: ${{  github.event.inputs.release_tag }}
          base_branch: ${{  github.event.inputs.base_branch }}
          github_token: ${{ steps.generate_token.outputs.token }}

